//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErDbBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public int ID { get; set; }
        public string TIME { get; set; }
        public string DATE { get; set; }
        public bool RESERVED { get; set; }
        public string EMAIL { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
    }
}
